/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javasimplenotepad;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.UndoManager;

/**
 *
 * @author thinkpad
 */
public class SimpleNotepad extends javax.swing.JFrame {

    /**
     * Creates new form SimpleNotePad
     */
    private String path;
    private String fileName;
    private Boolean lineWrap = true;
    private UndoManager um = new UndoManager();

    public SimpleNotepad() {
        initComponents();
        this.setTitle("Simple Notepad");

        jTextArea1.getDocument().addUndoableEditListener(
                new UndoableEditListener() {
            @Override
            public void undoableEditHappened(UndoableEditEvent e) {
                um.addEdit(e.getEdit());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUndo = new javax.swing.JMenuItem();
        menuRedo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuWordWrap = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuThemeLight = new javax.swing.JMenuItem();
        menuThemeDark = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        jMenu1.add(menuNew);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpen.setText("Open");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSaveAs.setText("Save As");
        menuSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(menuSaveAs);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUndo.setText("Undo");
        menuUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUndoActionPerformed(evt);
            }
        });
        jMenu2.add(menuUndo);

        menuRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuRedo.setText("Redo");
        menuRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRedoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRedo);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Format");

        menuWordWrap.setText("Word Wrap : Enabled");
        menuWordWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWordWrapActionPerformed(evt);
            }
        });
        jMenu4.add(menuWordWrap);
        menuWordWrap.getAccessibleContext().setAccessibleName("");

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Color");

        menuThemeLight.setText("Light");
        menuThemeLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemeLightActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemeLight);

        menuThemeDark.setText("Dark");
        menuThemeDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemeDarkActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemeDark);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Help");

        menuAbout.setText("About Simple Notepad");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        // TODO add your handling code here:
        if (path != null) {
            int result = JOptionPane.showConfirmDialog(this, "Do you want to save changes?", "Opening file", JOptionPane.YES_NO_OPTION);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    save();
                    open();
                    return;
                case JOptionPane.NO_OPTION:
                    open();
            }
        } else {
            open();
        }
    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
        if (path != null) {
            save();
        } else {
            saveAs();
        }
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveAsActionPerformed
        // TODO add your handling code here:
        saveAs();
    }//GEN-LAST:event_menuSaveAsActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        // TODO add your handling code here:
        if (path != null) {
            int result = JOptionPane.showConfirmDialog(this, "Do you want to save changes?", "Creating new file", JOptionPane.YES_NO_OPTION);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    save();
                    return;
                case JOptionPane.NO_OPTION:
                    jTextArea1.setText("");
                    path = null;
                    fileName = "New";
                    this.setTitle(fileName);
                    return;
            }
        } else {
            jTextArea1.setText("");
            path = null;
            fileName = "New";
            this.setTitle(fileName);
        }
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "A simple notepad with Java GUI.\n"
                + "\n"
                + "\n"
                + "My Github : oktavianoandy\n"
                + "Created with ❤ by Oktaviano Andy Suryadi.");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuWordWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWordWrapActionPerformed
        // TODO add your handling code here:
        if (lineWrap == true) {
            menuWordWrap.setText("Word Wrap : Disabled");
            lineWrap = false;
            jTextArea1.setLineWrap(false);
        } else {
            menuWordWrap.setText("Word Wrap : Enabled");
            lineWrap = true;
            jTextArea1.setLineWrap(true);
        }
    }//GEN-LAST:event_menuWordWrapActionPerformed

    private void menuThemeLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemeLightActionPerformed
        // TODO add your handling code here:
        jTextArea1.setBackground(Color.WHITE);
        jTextArea1.setForeground(Color.BLACK);
        jTextArea1.setCaretColor(Color.BLACK);
    }//GEN-LAST:event_menuThemeLightActionPerformed

    private void menuThemeDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemeDarkActionPerformed
        // TODO add your handling code here:
        jTextArea1.setBackground(Color.DARK_GRAY);
        jTextArea1.setForeground(Color.WHITE);
        jTextArea1.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_menuThemeDarkActionPerformed

    private void menuUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUndoActionPerformed
        // TODO add your handling code here:
        if (um.canUndo()) {
            um.undo();
        }
    }//GEN-LAST:event_menuUndoActionPerformed

    private void menuRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRedoActionPerformed
        // TODO add your handling code here:
        if (um.canRedo()) {
            um.redo();
        }

    }//GEN-LAST:event_menuRedoActionPerformed

    private void open() {
        jTextArea1.setText("");
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        path = fc.getSelectedFile().getPath();
        try {
            InputStream is = new FileInputStream(path);
            int data = is.read();
            while (data != -1) {
                jTextArea1.append(""+ (char) data);
                data = is.read();
            }

            is.close();
            fileName = fc.getSelectedFile().getName();
            this.setTitle(fileName + " - Simple Notepad");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void saveAs() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Specify a file to save");
        int userSelection = fc.showSaveDialog(jTextArea1);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getPath();
            File fileToSave = fc.getSelectedFile();

            fileName = fc.getSelectedFile().getName();
            this.setTitle(fileName + " - Simple Notepad");

            if (fileToSave.exists()) {
                int result = JOptionPane.showConfirmDialog(this, "The file is already exists, overwrite?", "Existing file", JOptionPane.OK_CANCEL_OPTION);
                switch (result) {
                    case JOptionPane.YES_OPTION:
                        save();
                        return;
                    case JOptionPane.CANCEL_OPTION:
                        return;
                }
            } else {
                save();
            }
        }
    }

    private void save() {
        try {
            OutputStream os = new FileOutputStream(path);
            String word = jTextArea1.getText();
            os.write(word.getBytes());
            os.flush();
            os.close();
            JOptionPane.showMessageDialog(this, "Save successful");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuRedo;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JMenuItem menuThemeDark;
    private javax.swing.JMenuItem menuThemeLight;
    private javax.swing.JMenuItem menuUndo;
    private javax.swing.JMenuItem menuWordWrap;
    // End of variables declaration//GEN-END:variables
}
